# CI de Nível 03 - Disparo automático sempre que outro for concluído (ex: deploy)
#nome que vai aparecer la nass opções da pipe
name: 'Execução por Deploy'

#triggersss OU gatilho de execução
  #gatilho de execução apó  outro workflow = workflow_run

on:
  workflow_run:
    workflows: ['Execução manual']
    types:
      - completed

jobs:

  # descrição do job
  e2e-tests:

    # máquina que o job vai executar
    runs-on: ['ubuntu-latest']

    if: ${{ github.event.workflow_run.conclusion == 'success'}}

    # passo a passso das ações do job
    steps:
    - uses: actions/checkout@v4

    - name: Instalando Yarn
      run: npm install -g yarn

    - name: Instalando dependências
      run: yarn

    - name: Instalando Playwright
      run: yarn playwright install

    - name: Testes E2E
      run: yarn run e2e

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: relatorio-de-testess
        path: ./playwright-report
  