# CI de Nível 04 - Disparo dentrodefluxo de CI de desenvolvimento
#nome que vai aparecer la nass opções da pipe
name: 'Execução Integrada'

#triggersss OU gatilho de execução
#gatilho de execução manual = workflow_dispatch

on:
  workflow_dispatch:

jobs:
  inspection:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Padronização de código (lint)
        run: yarn lint

  unit:
    runs-on: ['ubuntu-latest']

    needs: [inspection]

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Testes de unidade
        run: yarn run test

  # descrição do job
  e2e-tests:
    # máquina que o job vai executar
    runs-on: ['ubuntu-latest']

    needs: [unit]

    # passo a passso das ações do job
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Subir aplicação local
        run: yarn start &

      - name: Testes E2E
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000'

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testess
          path: ./playwright-report

  deploy:
    runs-on: ['ubuntu-latest']

    needs: [e2e-test]

    steps:
      - name: Deploy
        run: echo "step deploy"
